/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import model.Person_Info;

/**
 *
 * @author mhetr
 */
public class MainjFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainjFrame
     */
    
    Person_Info personInfo;
    public MainjFrame() {
        initComponents();
        
        personInfo = new Person_Info();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        split_Panel = new javax.swing.JSplitPane();
        control_Panel = new javax.swing.JPanel();
        btn_Create = new javax.swing.JButton();
        btn_Display = new javax.swing.JButton();
        work_Panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_Create.setText("Create Profile");
        btn_Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CreateActionPerformed(evt);
            }
        });

        btn_Display.setText("Display Profile");
        btn_Display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DisplayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout control_PanelLayout = new javax.swing.GroupLayout(control_Panel);
        control_Panel.setLayout(control_PanelLayout);
        control_PanelLayout.setHorizontalGroup(
            control_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(control_PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(control_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Create, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_Display, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        control_PanelLayout.setVerticalGroup(
            control_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(control_PanelLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(btn_Create)
                .addGap(55, 55, 55)
                .addComponent(btn_Display)
                .addContainerGap(422, Short.MAX_VALUE))
        );

        split_Panel.setLeftComponent(control_Panel);

        javax.swing.GroupLayout work_PanelLayout = new javax.swing.GroupLayout(work_Panel);
        work_Panel.setLayout(work_PanelLayout);
        work_PanelLayout.setHorizontalGroup(
            work_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 805, Short.MAX_VALUE)
        );
        work_PanelLayout.setVerticalGroup(
            work_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 783, Short.MAX_VALUE)
        );

        split_Panel.setRightComponent(work_Panel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(split_Panel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(split_Panel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CreateActionPerformed
        // TODO add your handling code here:
        
        Create_jPanel createPanel= new Create_jPanel(personInfo);
        split_Panel.setRightComponent(createPanel);
        
    }//GEN-LAST:event_btn_CreateActionPerformed

    private void btn_DisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DisplayActionPerformed
        // TODO add your handling code here:
        Display_jPanel displayPanel= new Display_jPanel(personInfo);
        split_Panel.setRightComponent(displayPanel);
    }//GEN-LAST:event_btn_DisplayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainjFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainjFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainjFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainjFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainjFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Create;
    private javax.swing.JButton btn_Display;
    private javax.swing.JPanel control_Panel;
    private javax.swing.JSplitPane split_Panel;
    private javax.swing.JPanel work_Panel;
    // End of variables declaration//GEN-END:variables
}
